#!/usr/bin/env perl

use strict;
use warnings;

use Getopt::Long;
use Helpers;
use VelDatFile;

## Provide usage information
my $usage_text =
"Usage: $0 accepts these parameters:\n" .
"  (opt) '-i' will interactively request all parameters\n" .
"  (req only if interactive) Name of file containing desired UWIs\n" .
"  (req) Name of Velocity Data export file (VelSrv_ALL.csv)\n" .
"  (req) Name of output file to create\n";
my $ask;
GetOptions("i" => \$ask);
unless ($#ARGV == 0 or $ask) { print STDERR $usage_text; exit 1 }

## If we're interactive, ask for everything; otherwise, grab what we're given
my ($uwi_file, $veldat_file, $output_file);
if ($ask) {
	$uwi_file = prompt_with "Enter name of file containing desired UWIs: ";
	$veldat_file = prompt_with "Enter name of Velocity Data export file: ";
	$output_file = prompt_with "Enter name of output file to create: "
} else {
	($veldat_file) = @ARGV
}

## Gather a list of UWI's on stdin
my %uwis;
if ($ask) {
	open(UWIS, $uwi_file) or die "Could not open file $uwi_file\n";
	while (<UWIS>) {
		chomp;
		for (split /\r/) { $uwis{$_} = 1 }
	}
} else {
	while (<STDIN>) { chomp; $uwis{$_} = 1 }
}

## Open the Velocity Data file
my $input = VelDatFile->read($veldat_file);

## Open the output file
open OUTPUT, ">$output_file" or die;

## Print any checkshots for requested UWI's
while (my $record = $input->nextRecord) {
	$uwis{$record->getUwi} or next;
	if ($ask) {
		print OUTPUT $record->getCheckshot
	} else {
		print $record->getCheckshot
	}
}
