#!/usr/bin/env perl

use strict;
use warnings;

use PI297File;

## Provide usage information
die "Usage: $0 <input_file>\n" unless $#ARGV == 0;

## Gather a list of UWI's on stdin
my @uwis;
while (<STDIN>) { chomp && push @uwis, $_ }

## Open the PIDwight's 297 format file
my $input = PI297File->read($ARGV[0]);

## Print any directional surveys for requested UWI's
while (my $record = $input->nextRecord) {
	grep {$record->getUwi == $_} @uwis or next;
	print $record->getDirectionalSurvey
}
